FROM yandex/rep:0.6.5
MAINTAINER George Gilliver <george_gilliver@hotmail.co.uk>

#Install notebook addons
RUN pip install https://github.com/ipython-contrib/IPython-notebook-extensions/archive/master.zip 
